# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ "$HOSTNAME" != lhn.lola.whamcloud.com ]; then
    # modules don't work on login node
    module unload openmpi-x86_64
    module unload mpi/openmpi-x86_64
    module load mpich-x86_64
fi

IOD_HOME=/scratch/iod/
export IOD_INSTALL=$IOD_HOME
#export IOD_INSTALL=/scratch/iod/install/2014.05.22
AXE_HOME=/scratch/hdf/install/axe
LD_LIBRARY_PATH=$AXE_HOME/lib:$LD_LIBRARY_PATH

BMI_HOME=/scratch/hdf/bmi/default
LD_LIBRARY_PATH=$BMI_HOME/lib:$LD_LIBRARY_PATH

MERCURY_HOME=/scratch/hdf/mercury/default
LD_LIBRARY_PATH=$MERCURY_HOME/lib:$LD_LIBRARY_PATH

LD_LIBRARY_PATH=/scratch/hdf/install/opa/lib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=/scratch/hdf/build/H5Part/build/lib:$LD_LIBRARY_PATH

LD_LIBRARY_PATH=/usr/local/lib64:/usr/lib64:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$IOD_INSTALL/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$IOD_INSTALL/include:$C_INCLUDE_PATH
export CPP_INCLUDE_PATH=$IOD_INSTALL/include:$C_INCLUDE_PATH
export LIBRARY_PATH=$IOD_INSTALL/lib:$LIBRARY_PATH
PATH=$IOD_INSTALL/bin:$IOD_INSTALL/scripts:$IOD_INSTALL/sbin:$PATH
PATH=/usr/lib64/mpich/bin:$PATH
PATH=/scratch/hdf/install/autotools/bin:$PATH
export PATH
export LD_LIBRARY_PATH

. $IOD_HOME/config/setcluster.sh

function s() { ssh lola-$@; }

function mygo() { cd `$IOD_HOME/scripts/go "$@"`; }
alias go=mygo
#alias go="cd \`$IOD_HOME/scripts/go !*\`"

export I_MPI_PLATFORM=auto

# some flags to build the lanl fs-test binary
export MY_MPI_HOST="lola"
export MPI_LD="-lm -L/scratch/iod/lib -liod -O0"
export MPI_INC="-DHAS_PLFS -DHAS_IOD -I/scratch/iod/include -O0 -DMYSQL_FILE=/scratch/iod/output/$MY_MPI_HOST.fs_test.db"
export FS_TEST_EXTRA="/scratch/iod/scripts/iod_fs_test_extra.sh"
